### ISSUE TITLE
transfer from smb share to local disk

### ISSUE THREAD

**Issue by wgnoehring** [IMTEK-Simulation/dtool-smb#1]
Putting a dataset on a SMB share works well, but subsequently retrieving it raises an error, which turns out to be a bit of a rabbit hole.

Create a test dataset  `test_dataset`:
```
.
├── data
│   ├── bar
│   ├── baz
│   │   └── baz
│   └── foo
└── README.yml
```
Copy the dataset to a SMB share:

```
dtool cp test_dataset smb://<name>
```

Try to retrieve the dataset:

```
dtool cp smb://<share>/<hash> ./
```

dtool will raise  `NotImplementedError` because the SMB storage broker does not have a method 
`get_item_abspath`. It seems at first that this is a trivial method name problem, because there is a 
method `get_item_path`. I think this method should be renamed. Moreover, the method is currently broken because it sets `relpath = hitem["relpath"]`, where `hitem` is undefined. I think it should look as follows: 
```
    def get_item_abspath(self, identifier):
        """Return absolute path at which item content can be accessed.

        :param identifier: item identifier
        :returns: absolute path from which the item content can be accessed
        """
        manifest = self.get_manifest()
        relpath = manifest["items"][identifier]["relpath"]
        item_path = os.path.join(self._data_path, relpath)
        return item_path
```
However, even with this fix, the transfer still fails. It seems that `dtool` calls `storagebroker.put_item` from its default storage broker (rather than `dtool_smb.storagebroker.put_item`). And even it it were
to call `dtool_smb.storagebrooker`, it would result in a call to `pysmb.SMBConnection.storeFile`, 
which is the correct method only for transfer *to* the SMB share. For transfer from SMB to the local machine, we would have to use `pysmb.SMBConnection.retrieveFile`. In my opinion, this points to
a problem with the `BaseStorageBroker` base class: why is there a method `put_item`, but no `get_item`?

**Comment by jotelha** [comment]
Looks like the whole thing was designed to use "dtool cp" only one-way, from local to remote. This https://github.com/IMTEK-Simulation/dtool-smb/commit/130c803b27f07e52e1a1bd6173fc3dfbf0194795 together with this https://github.com/jotelha/dtoolcore/commit/d09347be5fd0d107991b90728f142793c7a34883 introduce your suggested get_item method, the transfer worked for a simple data set from samba share to local in my case. Does that work for you? That would however enforce modifications in all storage brokers .

**Comment by pastewka** [comment]
With the other storage brokers you can certainly copy the other direction. I'll look into this.

**Comment by jotelha** [comment]
It should be, according to https://dtool.readthedocs.io/en/latest/quick_start_guide.html#copying-a-dataset-from-remote-storage-to-local-disk

But with the current design of _copy_content in the dtoolcore master branch, https://github.com/jic-dtool/dtoolcore/blob/6aff99531d1192f86512f662caf22a6ecd2198a5/dtoolcore/__init__.py#L226-L263, without referring to the source dataset's storage broker, I don't see how.

**Comment by wgnoehring** [comment]
@jotelha 130c803 and jotelha/dtoolcore@d09347b work. 

I tried to figure out how it works in the S3 backend, but couldn't.
